# Generated by Django 2.2 on 2020-04-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('major', models.CharField(default='', max_length=256)),
                ('number', models.IntegerField(default=1)),
                ('full_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('real_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('real_name', models.CharField(max_length=50)),
                ('class_in', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.StudentClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
