# Generated by Django 2.2 on 2019-12-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('real_name', models.CharField(max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('real_name', models.CharField(max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='1', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
