# Generated by Django 2.2 on 2019-12-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identity',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='identity',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2),
        ),
    ]
