# Generated by Django 2.2 on 2020-03-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('major', models.CharField(default='', max_length=256)),
                ('number', models.IntegerField(default=1)),
                ('full_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='class_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.StudentClass'),
        ),
    ]
