# Generated by Django 2.2 on 2019-12-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191210_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identity',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='1', max_length=2),
        ),
    ]
