# Generated by Django 2.2 on 2020-03-31 04:07

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import record.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitCodeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('ext', models.TextField(blank=True, default='')),
                ('problem_id', models.IntegerField(default=0)),
                ('commit_times', models.IntegerField(default=0)),
                ('src_content', models.TextField(default='')),
                ('src_saved_path', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitMissionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(default='', max_length=50)),
                ('mission_id', models.IntegerField(default=0)),
                ('saved_path', models.CharField(default='', max_length=256)),
                ('grade', models.CharField(default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompileSrcRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('exe_path', models.CharField(default='', max_length=256)),
                ('ext', models.TextField(default='')),
                ('success', models.BooleanField(default=False)),
                ('commit_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='record.CommitCodeRecord')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('ext', models.TextField(blank=True, default='')),
                ('email_type', models.CharField(max_length=256)),
                ('recipients', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificationSentRecord',
            fields=[
                ('emailsentrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record.EmailSentRecord')),
                ('active_code', models.CharField(default='', max_length=50)),
                ('token', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('record.emailsentrecord',),
        ),
        migrations.CreateModel(
            name='VerifyCodeSentRecord',
            fields=[
                ('emailsentrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record.EmailSentRecord')),
                ('code', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('record.emailsentrecord',),
        ),
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('result', django_mysql.models.JSONField(default=record.models.judge_result)),
                ('compile_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='record.CompileSrcRecord')),
            ],
        ),
    ]
