# Generated by Django 2.2 on 2020-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmissionrecord',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
