# Generated by Django 2.2 on 2020-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courseware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(default='', max_length=256)),
                ('file_path', models.CharField(default='', max_length=256)),
                ('file_type', models.CharField(choices=[('0', 'Other'), ('1', 'Video'), ('2', 'PDF')], default='1', max_length=2)),
                ('show_path', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
    ]
