# Generated by Django 2.2 on 2020-03-28 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200328_1101'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='student',
        #     name='class_in',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.StudentClass'),
        # ),
    ]
