# Generated by Django 2.2 on 2020-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseware',
            name='show_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='courseware',
            name='file_type',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'PPT'), ('2', 'Video'), ('3', 'PDF')], default='1', max_length=2),
        ),
    ]
