# Generated by Django 2.2 on 2020-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0002_auto_20200320_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseware',
            name='file_type',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Video'), ('2', 'PDF')], default='1', max_length=2),
        ),
    ]
