# Generated by Django 2.2 on 2020-03-19 09:11

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import apps.notice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_list', django_mysql.models.JSONField(default=apps.notice.models.appendix)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(default='', max_length=256)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('announce_at', models.DateTimeField(default=apps.notice.models.announce_time)),
                ('email_alert', models.BooleanField(default=False)),
                ('with_appendix', models.BooleanField(default=False)),
                ('appendix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notice.Appendix')),
            ],
        ),
    ]
