# Generated by Django 2.2 on 2020-03-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='to_class',
            field=models.CharField(default='', max_length=255),
        ),
    ]
