# Generated by Django 2.2 on 2019-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('ext', models.TextField(blank=True, default='')),
                ('operation', models.CharField(default='change password', editable=False, max_length=50)),
                ('old_password', models.CharField(default='', max_length=256)),
                ('new_password', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCertificationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('ext', models.TextField(blank=True, default='')),
                ('operation', models.CharField(default='certificate email', editable=False, max_length=50)),
                ('email', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailSentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('ext', models.TextField(blank=True, default='')),
                ('operation', models.CharField(default='send email', editable=False, max_length=20)),
                ('email_type', models.CharField(max_length=256)),
                ('recipients', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('identity', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('ext', models.TextField(blank=True, default='')),
                ('operation', models.CharField(default='login', editable=False, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificationSentRecord',
            fields=[
                ('emailsentrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record.EmailSentRecord')),
                ('active_code', models.CharField(default='', max_length=50)),
                ('token', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('record.emailsentrecord',),
        ),
        migrations.CreateModel(
            name='VerifyCodeSentRecord',
            fields=[
                ('emailsentrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record.EmailSentRecord')),
                ('code', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('record.emailsentrecord',),
        ),
    ]
