# Generated by Django 2.2 on 2019-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changepasswordrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailcertificationrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailsentrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loginrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='changepasswordrecord',
            name='account',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='changepasswordrecord',
            name='identity',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='emailcertificationrecord',
            name='account',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='emailcertificationrecord',
            name='identity',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='account',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='identity',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='account',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='identity',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=2),
        ),
    ]
