# Generated by Django 2.2 on 2019-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20191216_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepasswordrecord',
            name='old_password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='changepasswordrecord',
            name='new_password',
            field=models.CharField(default='', max_length=256),
        ),
    ]
