# Generated by Django 2.2 on 2019-12-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20191216_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCodeSentRecord',
            fields=[
                ('emailsentrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record.EmailSentRecord')),
                ('code', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('record.emailsentrecord',),
        ),
    ]
