# Generated by Django 2.2 on 2019-12-28 12:50

import apps.oj.models
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('detail', models.TextField(default='')),
                ('multiselect', models.BooleanField(default=False)),
                ('options', django_mysql.models.JSONField(default=apps.oj.models.choice_options)),
                ('answer', models.CharField(default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('detail', models.TextField(default='')),
                ('blank_num', models.IntegerField(default=1)),
                ('answers', django_mysql.models.JSONField(default=apps.oj.models.completion_answers)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('detail', models.TextField(default='')),
                ('input_demo', models.TextField(blank=True, default='')),
                ('output_demo', models.TextField(blank=True, default='')),
                ('time_claim', models.IntegerField(default=1000)),
                ('memory_claim', models.IntegerField(default=256)),
                ('test_case_in', models.CharField(blank=True, default='', max_length=256)),
                ('test_case_out', models.CharField(blank=True, default='', max_length=256)),
                ('test_case_cpp', models.CharField(blank=True, default='', max_length=256)),
                ('requirements', django_mysql.models.JSONField(default=dict)),
                ('ext', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
