# Generated by Django 2.2 on 2020-04-02 20:29

import apps.practice.models
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('detail', models.TextField(default='')),
                ('problem_type', models.CharField(choices=[('0', 'None'), ('1', 'Programme'), ('2', 'Choice')], default='2', editable=False, max_length=2)),
                ('multichoice', models.BooleanField(default=False)),
                ('options', django_mysql.models.JSONField(default=apps.practice.models.choice_options)),
                ('reference', models.CharField(default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('detail', models.TextField(default='')),
                ('problem_type', models.CharField(choices=[('0', 'None'), ('1', 'Programme'), ('2', 'Choice')], default='1', editable=False, max_length=2)),
                ('input_desc', models.TextField(blank=True, default='')),
                ('output_desc', models.TextField(blank=True, default='')),
                ('input_demo', models.TextField(blank=True, default='')),
                ('output_demo', models.TextField(blank=True, default='')),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=256)),
                ('testcase_count', models.IntegerField(default=0)),
                ('testcase_dir', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
